camel:
  springboot:
    main-run-controller: true
  component:
    kafka:
      brokers: localhost:9092
      client-id: consumer
      allow-manual-commit: true
      auto-commit-enable: false
      seek-to: ""
      auto-offset-reset: "earliest"
      break-on-first-error: true
      group-id: messaging-consumer-example
      value-deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
      schema-registry-u-r-l: http://localhost:8081
      additional-properties:
        "[specific.protobuf.value.type]": com.zandriod.consumer.proto.Timer
      poll-on-error: retry
  resilience4j:
    circuit-breaker:
      register-health-indicator: true


spring:
  webflux:
    base-path: "/consumer"
server:
  port: 8091

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
          - metrics
  health:
    jms:
      enabled: false
    ldap:
      enabled: false
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      enabled: true
      show-details: always
      probes:
        enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
    info:
      enabled: true


resilience4j:
  retry:
    instances:
      check:
        maxRetryAttempts: 3
        waitDuration: 100
        retryExceptions:
          - com.zandriod.consumer.exception.RecoverableException
        ignoreExceptions:
          - com.zandriod.consumer.exception.NonRecoverableException
          - com.zandriod.consumer.exception.BadClientRequestException
  circuitbreaker:
    metrics:
      enabled: true
    instances:
      check:
        wait-duration-in-open-state: 1m
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: count-based
        sliding-window-size: 5
        minimum-number-of-calls: 5
        slow-call-duration-threshold: 10s
        slow-call-rate-threshold: 60
        failure-rate-threshold: 60

  bulkhead:
    instances:
      check:
        maxConcurrentCalls: 10

