camel:
  springboot:
    main-run-controller: true
  component:
    kafka:
      brokers: localhost:9092
      client-id: consumer
      allow-manual-commit: true
      auto-commit-enable: false
      seek-to: ""
      auto-offset-reset: "latest"
      break-on-first-error: true
      group-id: messaging-consumer-example
      value-deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
      schema-registry-u-r-l: http://localhost:8081
      additional-properties:
        "[specific.protobuf.value.type]": com.zandriod.consumer.proto.Timer
      poll-on-error: reconnect

spring:
  webflux:
    base-path: "/consumer"
server:
  port: 8091

